# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170606_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='imageUrl',
            field=models.CharField(default='http://camtech.must.ac.ug/wp-content/uploads/2013/11/default-pic.png', max_length=255),
        ),
    ]
